export enum OrderStatus {
  ORDER_PLACED = "ORDER_PLACED",
  ORDER_PENDING = "ORDER_PENDING",
  ACTIVE = "ACTIVE",
  PARTIALLY_FILLED = "PARTIALLY_FILLED",
  FILLED = "FILLED",
  COMPLETED = "COMPLETED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
}